language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gnupg xclip git gnupg-agent
install: cpanm --quiet --notest JSON Try::Tiny Expect
script: make testjail
